### WC 25th September
- 1 hour: First supervisor meeting

### WC 02nd October
- 2 hours: Research

### WC 09th October
- 2 Hours: Research
- 6 hours Creating git repo/ creating django web app with some sample widgets/connecting the device.

### WC 16th October
- 10 Hours: Created native app to interact with the widgets and send pulse to electrotactile device.

### WC 23th October
- 10 Hours: Made improvements to the app - bug fixes and creating dials to control frequency, pulsewidth and amplitude parameters

### WC 30th October
- 7 Hours: made refactorings to the app 

### WC 06th November
- 5 Hours: Added feature to save the csv of the results.

### WC 13th November
- 10 Hours: began filling out ethics checklists in order to run user experiments

### WC 20th November
- 5 Hours: Wrote Questionnaire

### WC 27th November
- 5 hours: Ran pilot experiment, made required changes, started planning out actual experiment

### WC 04th December
- 10 Hours: Recruiting participants for phase one experiment

### WC 11th December
- 12 Hours: performing user experiments
- 20 Hours: Performing analysis on the results.

### WC 18th December
- 5 Hours: Running evaluation a few extra times.

### WC 25th December
- 0 Hours: Holliday

### WC 01st January
- 8 Hours: Continued analysis of the first studies results, produced charts.
- 8 Hours: Making code changes to application ready for second evaluation.

### WC 08th January
- 10 Hours: Making code changes to application for second application

### WC 15th January
- 15 Hours: running second evaluation

### WC 22nd January
- 10 hours: Analysing results of second evaluation/producing charts etc

### WC 29th January
- 10 Hours: Preparing app for final evaluation.

### WC 05th February
- 10 Hours: Preparing app for final evaluation.

### WC 12th February
- 10 Hours: Preparing app for final evaluation.
- 5 hours: Begin dissertation writing (headers etc).

### WC 19th February
- 15 Hours: Dissertation writing

### WC 26th February
- 15 Hours: Dissertation writing

### WC 04th March
- 12 Hours: running final evaluation.
- 5 Hours: Processing results of final evaluation.
- 3 Hours: Dissertation writing.

### WC 11th March
- 5 Hours: Processing results of final evaluation.
- 25 Hours: Dissertation writing.

### WC 18th March
- 30 Hours: Finishing dissertation
- 8 Hours: Planning and recording presentation video
- 5 Hours: Admin for submission
